#!/usr/bin/env python3
"""
Builds a Herb Codex card from art we already own plus data we already trust.

Why this exists, and why it does not call an image model:

Eighteen of the twenty cards were generated by prompting an image model, and
they are lovely. But a codex card is not only a picture — it carries the
herb's nature, flavour, channels entered and clinical note, and every one of
those is examinable material. Image models garble text and invent plausible
substitutes, and Ting's own art brief already draws the line:

    「如果哪一張你覺得『好像不太對但說不上來』，那就先不要放上去 ——
      寧可先用文字印版，也不要教錯本草。」

So the picture comes from the character portrait she already approved, and
every word on the card is read out of data/herbs.js at build time. The card
and the codex cannot disagree, because they are the same sentence.

    python3 tools/mkherbcard.py fuling gouqi     # or no args to rebuild all
"""
import os, re, sys, json, subprocess
from PIL import Image, ImageDraw, ImageFont, ImageFilter

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART  = os.path.join(HERE, "art")

SIZE      = 1000
PAPER     = (238, 228, 203)
INK       = (58, 50, 38)
INK_SOFT  = (104, 92, 72)
RULE      = (166, 148, 116)
PANEL_W   = 372          # the text column, matching the existing cards
PAD       = 40

CJK = "/usr/share/fonts/opentype/noto/NotoSerifCJK-Regular.ttc"
CJK_TC = 3               # the collection holds JP, KR, SC, TC, HK in that order

# Where the character sits in each portrait, as a fraction of its width, and
# how much to enlarge it. The portraits were drawn centred, so dropping a text
# column over the left third would slice the character in half — these move it
# clear. Eyeballed once per herb; a new herb without an entry falls back to the
# middle, which is right for a centred portrait on a card with no panel.
FOCUS = {
    "fuling": (0.55, 1.28),
    "gouqi":  (0.47, 1.30),
}


def font(size, bold=False):
    names = (["LiberationSerif-Bold.ttf", "DejaVuSerif-Bold.ttf"] if bold
             else ["LiberationSerif-Regular.ttf", "DejaVuSerif.ttf"])
    for root, _, files in os.walk("/usr/share/fonts"):
        for n in names:
            if n in files:
                return ImageFont.truetype(os.path.join(root, n), size)
    return ImageFont.load_default()


def cjk(size):
    """Latin faces have no Han glyphs — without this the Chinese renders as
    empty boxes, or as nothing at all, which is how the first draft shipped a
    card whose 漢字 name was simply missing."""
    try:
        return ImageFont.truetype(CJK, size, index=CJK_TC)
    except Exception:
        return font(size)


def herbs():
    """Read data/herbs.js the same way the game does, so there is one source."""
    js = os.path.join(HERE, "data", "herbs.js")
    out = subprocess.run(
        ["node", "-e",
         "global.window={};require(%r);process.stdout.write(JSON.stringify(window.AG_HERBS))" % js],
        capture_output=True, text=True, check=True)
    return {h["id"]: h for h in json.loads(out.stdout)}


def wrap(d, text, f, width):
    lines, line = [], ""
    for word in text.split():
        probe = (line + " " + word).strip()
        if d.textlength(probe, font=f) > width and line:
            lines.append(line); line = word
        else:
            line = probe
    if line: lines.append(line)
    return lines


def label(d, x, y, text, f):
    """A small dark plaque with the section name, as on the existing cards."""
    w = d.textlength(text, font=f)
    d.rounded_rectangle([x - 8, y - 5, x + w + 10, y + 22], 4, fill=(74, 63, 47))
    d.text((x, y), text, font=f, fill=(240, 232, 212))
    return y + 34


def build(h):
    src = Image.open(os.path.join(HERE, h["img"])).convert("RGB")

    card = Image.new("RGB", (SIZE, SIZE), PAPER)

    # place the portrait so the character lands in the open right-hand area
    fx, zoom = FOCUS.get(h["id"], (0.5, 1.0))
    side = int(SIZE * zoom)
    art  = src.resize((side, side), Image.LANCZOS)
    art_centre = (PANEL_W + SIZE) // 2                 # middle of the open area
    ox = int(art_centre - fx * side)
    oy = (SIZE - side) // 2
    card.paste(art, (ox, oy))

    # veil the text column back toward paper, fading out rather than cutting —
    # a hard vertical edge reads as a mistake, a fade reads as paper
    veil_w = PANEL_W + 110
    strip  = card.crop((0, 0, veil_w, SIZE))
    paper  = Image.new("RGB", strip.size, PAPER)
    mask   = Image.new("L", strip.size)
    md     = ImageDraw.Draw(mask)
    for i in range(veil_w):
        solid = PANEL_W - 40
        a = 238 if i < solid else int(238 * max(0.0, 1 - (i - solid) / float(veil_w - solid)))
        md.line([(i, 0), (i, SIZE)], fill=a)
    card.paste(Image.composite(paper, strip, mask), (0, 0))

    d = ImageDraw.Draw(card)

    f_name = font(60, True)
    f_py   = font(25)
    f_en   = font(27)
    f_lab  = font(15, True)
    f_body = font(19)
    f_note = font(18)

    x, y = PAD, 44
    d.text((x, y), h["en"].upper() if len(h["en"]) < 14 else h["en"], font=f_name, fill=INK)
    y += 74
    d.text((x, y), h["py"], font=f_py, fill=INK_SOFT); y += 36
    d.text((x, y), h["zh"], font=cjk(30), fill=INK_SOFT); y += 48
    d.line([x, y, x + PANEL_W - PAD, y], fill=RULE, width=2); y += 26

    # nature and flavour, then channels — one field in the data, two on the card
    nature = h["nature"]
    flavour, _, channels = nature.partition("·")
    y = label(d, x, y, "NATURE & FLAVOUR", f_lab)
    for ln in wrap(d, flavour.strip(), f_body, PANEL_W - PAD - 10):
        d.text((x, y), ln, font=f_body, fill=INK); y += 27
    y += 16

    if channels.strip():
        y = label(d, x, y, "CHANNELS ENTERED", f_lab)
        for ln in wrap(d, channels.strip(), f_body, PANEL_W - PAD - 10):
            d.text((x, y), ln, font=f_body, fill=INK); y += 27
        y += 16

    y = label(d, x, y, "WHAT IT DOES", f_lab)
    for ln in wrap(d, h["fact"], f_note, PANEL_W - PAD - 10):
        d.text((x, y), ln, font=f_note, fill=INK); y += 26

    # Chinese support sits at the foot of the column, the same relationship the
    # game keeps everywhere: English is the line, Chinese is the help under it
    zh_body = cjk(17)
    lines = []
    for text in (h.get("natureZh", ""), h.get("factZh", "")):
        if not text: continue
        # Chinese wraps by character, not by space — but never leave a closing
        # mark stranded at the head of a line, which is how the first draft put
        # a lone 。 on a line of its own.
        CLOSERS = "。，、；：？！」』）】"
        buf = ""
        for ch in text:
            if d.textlength(buf + ch, font=zh_body) > PANEL_W - PAD - 10 and ch not in CLOSERS:
                lines.append(buf); buf = ch
            else:
                buf += ch
        if buf: lines.append(buf)
        lines.append("")
    if lines and lines[-1] == "": lines.pop()

    y = SIZE - 46 - len(lines) * 27
    d.line([x, y - 20, x + PANEL_W - PAD, y - 20], fill=RULE, width=1)
    for ln in lines:
        d.text((x, y), ln, font=zh_body, fill=INK_SOFT); y += 27

    out = os.path.join(ART, "card-%s.jpg" % h["id"])
    card.save(out, quality=90)
    print("  card-%-12s %s" % (h["id"] + ".jpg", card.size))
    return out


if __name__ == "__main__":
    H = herbs()
    ids = sys.argv[1:] or sorted(H)
    for i in ids:
        if i not in H:
            print("  ! no herb called %r in data/herbs.js" % i); continue
        build(H[i])
